title: Shaw Talebi
#logo: /assets/img/headshot_circle.png
description: A highly motivated and results-oriented IT Engineer seeking an opportunity to contribute my skills and expertise in [Your Field]. Committed to achieving organizational goals through strategic planning, effective communication, and diligent execution.
#show_downloads: true
theme: Jekyll-theme-minimal
